version: '2.0'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=umdio
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5433
  redoc:
    image: redocly/redoc
    environment:
      - SPEC_URL=http://localhost:3000/v1/spec.yaml
    ports:
      - 8080:80
  umdio:
    build: .
    links:
      - postgres
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
    command: bundle exec rake up