version: "2.0"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=umdio
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  umdio:
    build: .
    links:
      - postgres
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
    command: bundle exec rake up
    restart: always
