version: "3.8"
services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=umdio
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  # UMD.io Server
  umdio:
    build: .
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: bundle exec rake up
    restart: always
