version: '2.0'
services:
  mongodb:
    image: mongo:3.2.17
    command: mongod --port 27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=umdio
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5433
  redoc:
    image: redocly/redoc
    environment:
      - SPEC_URL=http://localhost:3000/v0/spec.yaml
    ports:
      - 8080:80
  umdio:
    build: .
    links:
      - mongodb
      - postgres
    environment:
      - MONGO_RUBY_DRIVER_HOST=mongodb
      - MONGO_RUBY_DRIVER_PORT=27017
    volumes:
      - ./:/umdio
    ports:
      - 3000:3000
    command: bundle exec rake up