require 'rspec/core/rake_task'
#require File.expand_path('../config/application', __FILE__)
 
namespace :db do
  desc "Build Database"
  task :up => ['db:down'] do
    sh 'mongod --dbpath ./data/db --fork --logpath ./data/mongo/mongodb.log' #works on mac, but not ubuntu
  end

  desc "Shutdown mongo database server"
  task :down do
    mongo_pid = `pgrep mongod`
    if (!mongo_pid.empty?) then
      puts "DANGER: killing mongod instances: #{mongo_pid}"
      mongo_pid.split("\n").each{|pid| Process.kill(15,pid.to_i)}
    else
      puts 'No mongod processes found -- free to go ahead'
    end
  end
end

desc "Scrape testudo to fill the database"
task :scrape => ['db:up'] do
  ruby 'app/helpers/courses_scraper.rb'
end

task :setup => ['scrape']

desc "Start the web server"
task :up do
  #if ENV['RACK_ENV'] == :development
  `shotgun -p 3000`
end
task :server => :up

desc "Run tests in /tests that look like *_spec.rb"
RSpec::Core::RakeTask.new :test do |task|
  task.pattern = Dir['tests/**/*_spec.rb']
  task.rspec_opts = "--format documentation" #default to verbose testing, comment for silence
end
task :spec => :test

desc "Generate static docs files"
task :docs do
  require 'jekyll'
  src = File.expand_path('./docs/src/')

  # copy main.scss and add jekyll header
  input = src + '/_sass/main.scss'
  output = src + '/css/main.scss'
  File.open(output, 'w') do |file|
    file.puts "---\n# Auto-generated by rake docs\n---"
    File.foreach(input) { |line| file.puts line }
  end

  # jekyll build
  conf = Jekyll.configuration({
    'source' => src,
    'destination' => File.expand_path('./docs/public/'),
  })
  Jekyll::Site.new(conf).process
end

task :default => ['test']
