version: 2
jobs:
  build:
    machine: true
    working_directory: ~/umdio
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run docker-compose
          command: |
            docker-compose pull
            docker-compose build
            docker-compose up -d
            sleep 4
            docker exec -it umdio_umdio_1 bundle exec rake test_scrape
            docker exec -it umdio_umdio_1 bundle exec rake