module Jekyll
  # automatically copies sass files to css and adds frontmatter
  class ScssGenerator < Generator
    def generate(site)
      scss_files = Dir[site.source + "/_sass/[^_]*.scss"]
      scss_files.each do |input|
        filename = input.split('/').last
        output = site.source + "/css/" + filename

        File.open(output, 'w') do |file|
          file.puts "---\n# Auto-generated by Jekyll _plugins/generators.rb\n---"
          File.foreach(input) { |line| file.puts line }
        end
      end
    end
  end
end
